apiVersion: v1
kind: ConfigMap
metadata:
  name: php-login-config
  namespace: php-login-app
  labels:
    app: php-login
data:
  USER_ENHANCEMENT: "true"
  STAGE: "pre-production"
  SERVICE_NAME: "php_login"
